name: crane
channels:
  - cmriprocan
  - defaults
  - anaconda
  - plotly
  - p-vg
  - conda-forge
  - bioconda
dependencies:
  - anndata
  - toffee=0.14.2
  - ca-certificates
  - certifi
  - docker-py
  - docker-pycreds
  - openssl
  - websocket-client
  - xorg-libxau
  - xorg-libxdmcp
  - anaconda-client
  - appdirs
  - asn1crypto
  - atomicwrites
  - attrs
  - automat
  - backcall
  - beautifulsoup4
  - blas
  - bleach
  - boost=1.67.0
  - boost-cpp=1.67.0
  - bzip2
  - cffi
  - chardet
  - clyent
  - conda
  - conda-build
  - conda-env
  - constantly
  - cryptography
  - cryptography-vectors
  - cycler
  - dbus
  - decorator
  - eigen=3.3.5
  - entrypoints
  - expat
  - filelock
  - fontconfig
  - freetype
  - gettext
  - glib
  - glob2
  - gmp
  - gst-plugins-base
  - gstreamer
  - h5py
  - hdf5=1.10.2
  - html5lib
  - hyperlink
  - icu
  - idna
  - incremental
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - kiwisolver
  - libboost
  - libedit
  - libffi
  - libiconv
  - libopenblas
  - libpng
  - libsodium
  - libuuid
  - libxcb
  - libxml2
  - markupsafe
  - matplotlib=3.1.1
  - mistune
  - more-itertools
  - natsort
  - nbconvert
  - nbformat
  - ncurses
  - nomkl
  - notebook
  - numpy=1.15.1=py36_blas_openblashd3ea46f_1
  - numpy-base
  - openblas
  - openblas-devel
  - packaging
  - pandas=0.25.1
  - pandoc
  - pandocfilters
  - parso
  - patsy
  - pcre
  - pexpect
  - pickleshare
  - pip
  - pkginfo
  - plotly
  - pluggy
  - prometheus_client
  - prompt_toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - py
  - py-boost
  - pyasn1
  - pyasn1-modules
  - pycosat
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pysocks
  - pytest
  - pytest-runner
  - python
  - python-dateutil
  - pytz
  - pywavelets=1.0.3
  - pyyaml
  - pyzmq
  - qt
  - qtconsole
  - readline
  - requests
  - retrying
  - ruamel_yaml
  - scipy=1.1.0
  - seaborn=0.9.0
  - send2trash
  - service_identity
  - setuptools
  - simplegeneric
  - sip
  - six
  - sqlite
  - statsmodels
  - terminado
  - testpath
  - tk
  - tornado
  - tqdm
  - traitlets
  - twisted
  - urllib3
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - xlrd
  - xz
  - yaml
  - zeromq
  - zlib
  - zope
  - zope.interface
  - boto3
  - plotly-orca
